# These are supported funding model platforms 

patreon: https://patreon.com/JamesDominicLiao_Nicoliao0918 
ko_fi: buymeacoffee.com/nicoliao12q 
buy_me_a_coffee: ko-fi.com/jamesliao 
paypal: https://paypal.me/liaoPH09
